spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/mysql
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create-drop
    properties:
      hibernate:format_sql: true
    show-sql: true

  security:
    user:
      password: 1

jwt:
  secret: MjFmcnlmc2RmamE3OXlZRnNkRnN5ZGY5eWZzZGhnSGdxZWc0Mwo=